CREATE TABLE IF NOT EXISTS user_avatars (
  user_id INT PRIMARY KEY,
  mime_type VARCHAR(30) NOT NULL,
  image MEDIUMBLOB NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
